image: node:latest

stages:
    - build
    - test

cache:
    paths:
        - node_modules/

Dependencies:
    stage: build
    script:
        - npm install

Testing:
    stage: test
    script: npm test
